---
- name: Copy Docker service file
  hosts: all
  become: yes

  tasks:
    - name: Copy docker.service file
      template:
        src: /home/deb1i/template/docker.service
        dest: /lib/systemd/system/docker.service
      notify:
        - Restart Docker Service

  handlers:
    - name: Restart Docker Service
      systemd:
        name: docker
        state: restarted
