---
- name: Copy Docker service file
  hosts: all
  become: yes

  tasks:
    - name: Copy docker.service file
      copy:
        src: /home/deb1i/template/docker.service
        dest: /lib/systemd/system/docker.service
        remote_src: yes
